### ISSUE TITLE
[FEATURE]: Support python 3.14

### ISSUE THREAD

**Issue by asnare** [databrickslabs/lakebridge#2137]
### Problem statement

Python 3.14 has been released, and our documentation states that prior to installation:
> Verify that Python 3.10 or above is installed

However some of our dependencies do not support Python 3.14 at the moment. Problems include:

 - `install-tranpsiler` fails due to an import issues.
 - The BB plugin has code that is specific to platform and python version. Currently there is nothing in place for Python 3.14, which means it will not work.
 - Some (transitive) dependencies do not have wheels published for all platforms. For example, user reports suggest there are problems with `duckdb` and `pyodbc` on Windows.

(There might be more problems than just this.)

### Proposed Solution

In the short term:

 - Update the documentation to mention that Python 3.14 doesn't currently work.

In the medium term:

 - Update the project (including BB) to work with Python 3.14.

### Additional Context

Import issue during `install-transpile`:
```
20:03:56 Debug: starting: /Users/**REDACTED**/dev/lakebridge/.venv/bin/python3 /Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/cli.py {"command":"install-transpile","flags":{"artifact":"","include-llm-transpiler":"false","interactive":"auto","log_level":"debug"},"output_type":""} pid=83223
Traceback (most recent call last):
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/cli.py", line 27, in <module>
    from databricks.labs.lakebridge.contexts.application import ApplicationContext
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/contexts/application.py", line 21, in <module>
    from databricks.labs.lakebridge.deployment.installation import WorkspaceInstallation
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/deployment/installation.py", line 15, in <module>
    from databricks.labs.lakebridge.deployment.recon import ReconDeployment
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/deployment/recon.py", line 15, in <module>
    from databricks.labs.lakebridge.deployment.table import TableDeployment
  File "/Users/**REDACTED**/dev/lakebridge/src/databricks/labs/lakebridge/deployment/table.py", line 2, in <module>
    from importlib.abc import Traversable
ImportError: cannot import name 'Traversable' from 'importlib.abc' (/opt/homebrew/Cellar/python@3.14/3.14.0_1/Frameworks/Python.framework/Versions/3.14/lib/python3.14/importlib/abc.py)
Error: exit status 1
```
(Looks trivial.)
